import { Plan } from "@/lib/types/platform";
export const DEFAULT_PLANS: Plan[] = [
  {
    id: "PLAN-FREE",
    code: "free",
    name: "Free",
    monthlyPrice: 0,
    yearlyPrice: 0,
    trialDays: 0,
    active: true,
    description: "Simple money tracking to get started.",
    aiQuota: 5,
    transactionLimit: 100,
    accountLimit: 1,
    features: ["basic_tracking", "monthly_report", "basic_ai"],
  },
  {
    id: "PLAN-PERSONAL",
    code: "personal",
    name: "Personal",
    monthlyPrice: 1500,
    yearlyPrice: 15000,
    trialDays: 14,
    active: true,
    description: "Complete personal money intelligence.",
    aiQuota: 60,
    transactionLimit: -1,
    accountLimit: 5,
    features: [
      "basic_tracking",
      "monthly_report",
      "quarterly_report",
      "yearly_report",
      "recurring",
      "money_health",
      "forecast",
      "csv_export",
      "pdf_export",
      "advanced_ai",
    ],
  },
  {
    id: "PLAN-BUSINESS",
    code: "business",
    name: "Business",
    monthlyPrice: 3500,
    yearlyPrice: 35000,
    trialDays: 14,
    active: true,
    description: "AI finance intelligence for traders and SMEs.",
    aiQuota: 200,
    transactionLimit: -1,
    accountLimit: 15,
    features: [
      "basic_tracking",
      "monthly_report",
      "quarterly_report",
      "yearly_report",
      "recurring",
      "money_health",
      "forecast",
      "csv_export",
      "pdf_export",
      "advanced_ai",
      "business_insights",
      "anomaly_detection",
      "reconciliation",
      "custom_reports",
    ],
  },
  {
    id: "PLAN-PRO",
    code: "pro",
    name: "Pro",
    monthlyPrice: 7500,
    yearlyPrice: 75000,
    trialDays: 14,
    active: true,
    description:
      "Advanced intelligence, multi-profile capability and premium controls.",
    aiQuota: 1000,
    transactionLimit: -1,
    accountLimit: -1,
    features: [
      "basic_tracking",
      "monthly_report",
      "quarterly_report",
      "yearly_report",
      "recurring",
      "money_health",
      "forecast",
      "csv_export",
      "pdf_export",
      "advanced_ai",
      "business_insights",
      "anomaly_detection",
      "reconciliation",
      "custom_reports",
      "multi_profile",
      "priority_support",
      "premium_exports",
    ],
  },
  {
    id: "PLAN-UNLIMITED",
    code: "unlimited",
    name: "Unlimited",
    monthlyPrice: 0,
    yearlyPrice: 0,
    trialDays: 0,
    active: false,
    description:
      "Permanent unrestricted access for protected system administrators.",
    aiQuota: -1,
    transactionLimit: -1,
    accountLimit: -1,
    features: [
      "basic_tracking",
      "monthly_report",
      "quarterly_report",
      "yearly_report",
      "recurring",
      "money_health",
      "forecast",
      "csv_export",
      "pdf_export",
      "advanced_ai",
      "business_insights",
      "anomaly_detection",
      "reconciliation",
      "custom_reports",
      "multi_profile",
      "priority_support",
      "premium_exports",
      "platform_admin",
    ],
  },
];
