"use client";
import {useEffect,useMemo,useState} from "react";import Shell from "@/components/Shell";import AskCacsms from "@/components/AskCacsms";import {TrendChart,Donut} from "@/components/Charts";import {Icon} from "@/components/Icons";import {Transaction} from "@/lib/types/finance";
const money=(n:number)=>new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN",maximumFractionDigits:0}).format(n),sum=(a:Transaction[],t:string)=>a.filter(x=>x.type===t).reduce((s,x)=>s+x.amount,0);
function rangeFor(period:string,from:string,to:string){const n=new Date();if(period==="Monthly")return{start:new Date(n.getFullYear(),n.getMonth(),1),end:new Date(n.getFullYear(),n.getMonth()+1,0)};if(period==="Quarterly"){const q=Math.floor(n.getMonth()/3)*3;return{start:new Date(n.getFullYear(),q,1),end:new Date(n.getFullYear(),q+3,0)}}if(period==="Yearly")return{start:new Date(n.getFullYear(),0,1),end:new Date(n.getFullYear(),11,31)};return{start:new Date(from||n.toISOString().slice(0,10)),end:new Date(to||n.toISOString().slice(0,10))}}
export default function Reports(){const[txs,setTxs]=useState<Transaction[]>([]),[analysis,setAnalysis]=useState<any>(null),[period,setPeriod]=useState("Monthly"),[from,setFrom]=useState(new Date(new Date().getFullYear(),new Date().getMonth(),1).toISOString().slice(0,10)),[to,setTo]=useState(new Date().toISOString().slice(0,10)),[search,setSearch]=useState(""),[type,setType]=useState("all");
 useEffect(()=>{Promise.all([fetch("/api/transactions").then(r=>r.json()),fetch("/api/analysis").then(r=>r.json())]).then(([t,a])=>{setTxs(t);setAnalysis(a)})},[]);const range=rangeFor(period,from,to),current=useMemo(()=>txs.filter(t=>{const d=new Date(t.date);return d>=range.start&&d<=new Date(range.end.getTime()+86400000-1)}),[txs,period,from,to]);const income=sum(current,"income"),expense=sum(current,"expense"),net=income-expense;
 const cats=useMemo(()=>{const m=new Map<string,number>();current.filter(t=>t.type==="expense").forEach(t=>m.set(t.category,(m.get(t.category)||0)+t.amount));return[...m].map(([name,value])=>({name,value})).sort((a,b)=>b.value-a.value)},[current]);
 const trend=useMemo(()=>{const n=new Date();return Array.from({length:12},(_,i)=>{const d=new Date(n.getFullYear(),n.getMonth()-11+i,1),a=txs.filter(t=>{const z=new Date(t.date);return z.getMonth()===d.getMonth()&&z.getFullYear()===d.getFullYear()});return{label:d.toLocaleString("en",{month:"short"}),income:sum(a,"income"),expense:sum(a,"expense")}})},[txs]);
 const filtered=current.filter(t=>(type==="all"||t.type===type)&&(`${t.description} ${t.category} ${t.account}`.toLowerCase().includes(search.toLowerCase())));
 const exportHref=`/api/export?from=${range.start.toISOString().slice(0,10)}&to=${range.end.toISOString().slice(0,10)}`;
 return <Shell><div className="page reportsPage"><section className="welcome"><div><span className="eyebrow">REPORTS & INTELLIGENCE</span><h1>Understand what your money is doing.</h1><p>Review performance, trends, categories and Cacsms intelligence from your records.</p></div><a className="btn exportBtn" href={exportHref}>Export CSV</a></section><div className="reportToolbar"><div className="reportTabs">{["Monthly","Quarterly","Yearly","Custom"].map(x=><button key={x} className={period===x?"active":""} onClick={()=>setPeriod(x)}>{x}</button>)}</div>{period==="Custom"&&<div className="dateRange"><label>From<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div>}</div>
 <section className="heroGrid reportMetrics"><div className="metric"><p>Total income</p><h2>{money(income)}</h2><small>{current.filter(t=>t.type==="income").length} income entries</small></div><div className="metric"><p>Total expenses</p><h2>{money(expense)}</h2><small>{current.filter(t=>t.type==="expense").length} expense entries</small></div><div className="metric primaryMetric"><p>Net position</p><h2>{money(net)}</h2><small>{income?`${(net/income*100).toFixed(0)}% retained`:"No income recorded"}</small></div><div className="metric"><p>Money health</p><h2>{analysis?.score??"—"}<small className="scoreUnit">/100</small></h2><small>Current month health indicator</small></div></section>
 <section className="contentGrid"><article className="card"><div className="cardTitle"><div><span className="eyebrow">12-MONTH TREND</span><h3>Income and expense movement</h3></div><div className="legend"><span><i className="incomeDot"/>Income</span><span><i className="expenseDot"/>Expenses</span></div></div><TrendChart data={trend}/></article><article className="card"><div className="cardTitle"><div><span className="eyebrow">FORECAST</span><h3>Projected month-end</h3></div><span className="aiBadge"><Icon name="spark" size={14}/> AI estimate</span></div><div className="forecastMain"><small>Projected net position</small><strong>{money(analysis?.projectedNet||0)}</strong><p>Run-rate estimate based on transactions recorded so far this month.</p></div><div className="forecastRows"><div><span>Projected income</span><b>{money(analysis?.projectedIncome||0)}</b></div><div><span>Projected expenses</span><b>{money(analysis?.projectedExpenses||0)}</b></div><div><span>Confidence</span><b>Indicative</b></div></div></article></section>
 <section className="contentGrid lower"><article className="card"><div className="cardTitle"><div><span className="eyebrow">EXPENSE ANALYSIS</span><h3>Spending breakdown</h3></div></div><div className="categoryBody"><Donut items={cats}/><div className="categoryList">{cats.slice(0,8).map((c,i)=><div key={c.name}><span><i className={`catSwatch s${i}`}/>{c.name}</span><b>{money(c.value)}</b></div>)}{!cats.length&&<p className="empty">No expenses in this period.</p>}</div></div></article><article className="card aiDeep"><div className="cardTitle"><div><span className="aiBadge"><Icon name="spark" size={14}/> Cacsms AI Analysis</span><h3>What deserves your attention</h3></div></div><div className="analysisBlocks">{(analysis?.notes||[]).map((n:string,i:number)=><div key={i}><span className={i===1&&analysis?.expenseChange>0?"warn":"good"}>{i===1&&analysis?.expenseChange>0?"!":"✓"}</span><p>{n}</p></div>)}</div>{analysis?.anomaly&&<div className="warningStrip"><b>Unusual spending pattern</b><span>{analysis.anomaly.category} is {Math.round(analysis.anomaly.change)}% above last month.</span></div>}</article></section>
 <section className="card tableCard"><div className="cardTitle"><div><span className="eyebrow">TRANSACTION REGISTER</span><h3>Transactions in selected period</h3></div><div className="tableFilters"><input placeholder="Search transactions" value={search} onChange={e=>setSearch(e.target.value)}/><select value={type} onChange={e=>setType(e.target.value)}><option value="all">All types</option><option value="income">Money in</option><option value="expense">Money out</option></select></div></div><div className="tableWrap"><table><thead><tr><th>Date</th><th>Description</th><th>Category</th><th>Account</th><th>Method</th><th>Type</th><th className="num">Amount</th></tr></thead><tbody>{filtered.map(t=><tr key={t.id}><td>{new Date(t.date).toLocaleDateString("en-NG")}</td><td>{t.description||"—"}</td><td>{t.category}</td><td>{t.account}</td><td>{t.paymentMethod}</td><td><span className={t.type==="income"?"status incomeStatus":"status expenseStatus"}>{t.type==="income"?"Money In":"Money Out"}</span></td><td className="num"><b className={t.type==="income"?"incomeText":"expenseText"}>{t.type==="income"?"+":"−"}{money(t.amount)}</b></td></tr>)}{!filtered.length&&<tr><td colSpan={7} className="emptyCell">No transactions match this period and filter.</td></tr>}</tbody></table></div></section><section className="fullCard"><AskCacsms/></section></div></Shell>}
