import { NextResponse } from "next/server";
import { getFinanceRepository } from "@/lib/repositories";
import { Transaction } from "@/lib/types/finance";
const USER="USR-001";
function clean(body:any,base?:Transaction){const now=new Date().toISOString();return{date:String(body.date||base?.date||now),type:body.type||base?.type,amount:Number(body.amount??base?.amount),category:String(body.category||base?.category||"Other"),account:String(body.account||base?.account||"Main Account"),paymentMethod:body.paymentMethod||base?.paymentMethod||"Cash",description:String(body.description??base?.description??""),reference:String(body.reference??base?.reference??""),updatedAt:now}}
export async function GET(){return NextResponse.json(await getFinanceRepository().listTransactions(USER))}
export async function POST(req:Request){const body=await req.json(),now=new Date().toISOString(),v=clean(body);if(!v.amount||v.amount<0||!["income","expense"].includes(v.type))return NextResponse.json({error:"Enter a valid amount and transaction type."},{status:400});const tx:Transaction={id:`TXN-${Date.now()}-${Math.random().toString(36).slice(2,6).toUpperCase()}`,userId:USER,...v,createdAt:now} as Transaction;return NextResponse.json(await getFinanceRepository().createTransaction(tx),{status:201})}
export async function PATCH(req:Request){const body=await req.json();if(!body.id)return NextResponse.json({error:"Transaction ID is required."},{status:400});const updated=await getFinanceRepository().updateTransaction(String(body.id),USER,clean(body));return updated?NextResponse.json(updated):NextResponse.json({error:"Transaction not found."},{status:404})}
export async function DELETE(req:Request){const id=new URL(req.url).searchParams.get("id");if(!id)return NextResponse.json({error:"Transaction ID is required."},{status:400});const ok=await getFinanceRepository().deleteTransaction(id,USER);return ok?NextResponse.json({ok:true}):NextResponse.json({error:"Transaction not found."},{status:404})}
