"use client";
import {useEffect,useState} from "react";import {Icon} from "./Icons";import {Transaction} from "@/lib/types/finance";
const incomeCats=["Sales","Salary","Freelance","Business Income","Gift","Refund","Investment Income","Other Income"],expenseCats=["Stock Purchase","Transport","Food","Utilities","Rent","Fuel","Family","Education","Health","Airtime/Data","POS/Bank Charges","Business Expenses","Other Expense"];
export default function TransactionModal({onSaved}:{onSaved:()=>void}){const [open,setOpen]=useState(false),[type,setType]=useState<"income"|"expense">("income"),[saving,setSaving]=useState(false),[editing,setEditing]=useState<Transaction|null>(null),[error,setError]=useState("");
 useEffect(()=>{const add=(e:any)=>{setEditing(null);setType(e.detail?.type||"income");setError("");setOpen(true)},edit=(e:any)=>{setEditing(e.detail);setType(e.detail.type);setError("");setOpen(true)};window.addEventListener("open-add-transaction",add);window.addEventListener("edit-transaction",edit);return()=>{window.removeEventListener("open-add-transaction",add);window.removeEventListener("edit-transaction",edit)}},[]);
 if(!open)return null;async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setError("");const body=Object.fromEntries(new FormData(e.currentTarget).entries());if(editing)(body as any).id=editing.id;const r=await fetch("/api/transactions",{method:editing?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const data=await r.json();setSaving(false);if(!r.ok){setError(data.error||"Could not save transaction.");return}setOpen(false);onSaved()}
 const cats=type==="income"?incomeCats:expenseCats;
 return <div className="modalBackdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><form className="modal" onSubmit={submit}><div className="modalHead"><div><span className="eyebrow">{editing?"EDIT TRANSACTION":"QUICK ENTRY"}</span><h2>{editing?"Update transaction":"Record transaction"}</h2></div><button type="button" onClick={()=>setOpen(false)}>×</button></div>
 <div className="segmented"><button type="button" className={type==="income"?"selected incomeSel":""} onClick={()=>setType("income")}><Icon name="plus"/> Money In</button><button type="button" className={type==="expense"?"selected expenseSel":""} onClick={()=>setType("expense")}><Icon name="minus"/> Money Out</button></div><input type="hidden" name="type" value={type}/>
 <label className="amountField"><span>Amount</span><div><b>₦</b><input name="amount" required autoFocus inputMode="decimal" defaultValue={editing?.amount||""} placeholder="0"/></div></label>
 <div className="formGrid"><label>Category<select name="category" key={`${type}-${editing?.id||"new"}`} defaultValue={editing?.category||cats[0]}>{cats.map(x=><option key={x}>{x}</option>)}</select></label><label>Payment method<select name="paymentMethod" defaultValue={editing?.paymentMethod||"Cash"}><option>Cash</option><option>Bank Transfer</option><option>POS</option><option>Card</option><option>Wallet</option><option>Other</option></select></label><label>Date<input name="date" type="date" defaultValue={(editing?.date||new Date().toISOString()).slice(0,10)}/></label><label>Account<select name="account" defaultValue={editing?.account||"Main Account"}><option>Main Account</option><option>Cash</option><option>Bank</option><option>POS</option><option>Business Wallet</option></select></label></div>
 <label>Description<input name="description" defaultValue={editing?.description||""} placeholder="What was this for?"/></label><label>Reference <span className="optional">optional</span><input name="reference" defaultValue={editing?.reference||""} placeholder="Invoice, receipt or reference number"/></label>{error&&<p className="formError">{error}</p>}<div className="modalFoot"><button type="button" className="btn ghost" onClick={()=>setOpen(false)}>Cancel</button><button className="btn primary" disabled={saving}>{saving?"Saving...":editing?"Update transaction":"Save transaction"}</button></div></form></div>}
